version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Install packages
          command: |-
            cd backend/
            npm i
      - run:
          name: Lint code
          command: |-
            cd backend/
            npm run lint
      - run:
          name: JUnit
          command: |-
            npm i --save-dev jest
            npm i --save-dev jest-junit


      #- run:
      #    name: Install JUnit coverage reporter
      #    command: yarn add --dev jest-junit
      - run:
          name: Test code
          command: |-
            cd backend/
            npm test
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
            JEST_JUNIT_OUTPUT_NAME: report.xml
      - store_test_results:
          path: ./backend/reports/junit/
      - store_artifacts:
          path: ./backend/reports/junit/report.xml

      - run:
          name: Analyze code
          command: |-
            cd backend/
            npm audit --audit-level=critical



  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: |-
            cd frontend/
            npm i
      - run:
          name: Lint code
          command: |-
            cd frontend/
            npm run lint
      - run:
          name: Test code
          command: |-
            mkdir ~/frontend-test-results
            cd frontend/
            npm test
      - store_test_results:
          path: ~/frontend-test-results
      - store_artifacts:
          path: ~/frontend-test-results



workflows:
  default:
    jobs:
      - hello-world
      - build-backend:
          requires:
            - hello-world
      - build-frontend:
          requires:
            - build-backend