version: 2.1

jobs:
  hello-world:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Say Hello
          command: |
            echo "Hello World"
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run: 
          name: Install packages
          command: |-
            cd backend/
            npm i
      - run:
          name: Lint code
          command: |-
            cd backend/
            npm run lint

workflows:
  default:
    jobs:
      - hello-world
      - build-backend:
          requires:
            - hello-world